apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "slack.stakater.com/v1alpha1",
          "kind": "Channel",
          "metadata": {
            "name": "building-channel"
          },
          "spec": {
            "description": "Why is it called a 'building' if it's already built?",
            "name": "building-channel",
            "private": true,
            "topic": "Buildings",
            "users": [
              "hazim@stakater.com"
            ]
          }
        }
      ]
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.0.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v2
  name: slack-operator.v0.0.3
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Channel is the Schema for the channels API
      displayName: Channel
      kind: Channel
      name: channels.slack.stakater.com
      version: v1alpha1
  description: Kubernetes operator for Slack
  displayName: slack-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - secrets
          verbs:
          - get
          - list
        - apiGroups:
          - slack.stakater.com
          resources:
          - channels
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - slack.stakater.com
          resources:
          - channels/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: default
      deployments:
      - name: slack-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=10
                image: gcr.io/kubebuilder/kube-rbac-proxy:v0.5.0
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                resources: {}
              - args:
                - --metrics-addr=127.0.0.1:8080
                - --enable-leader-election
                command:
                - /manager
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: CONFIG_SECRET_NAME
                  value: slack-secret
                image: stakater/slack-operator:v0.0.3
                name: manager
                ports:
                - containerPort: 9443
                  name: webhook-server
                  protocol: TCP
                resources:
                  limits:
                    cpu: 100m
                    memory: 30Mi
                  requests:
                    cpu: 100m
                    memory: 20Mi
                volumeMounts:
                - mountPath: /tmp/k8s-webhook-server/serving-certs
                  name: cert
                  readOnly: true
              terminationGracePeriodSeconds: 10
              volumes:
              - name: cert
                secret:
                  defaultMode: 420
                  secretName: webhook-server-cert
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - configmaps/status
          verbs:
          - get
          - update
          - patch
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: default
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - operator
  - slack
  - kubernetes
  - channel
  - stakater
  - openshift
  links:
  - name: Slack Operator
    url: https://slack-operator.domain
  maturity: alpha
  provider:
    name: stakater
    url: https://stakater.com
  version: 0.0.3
  webhookdefinitions:
  - admissionReviewVersions: null
    deploymentName: slack-operator-webhook
    failurePolicy: Fail
    generateName: vchannel.kb.io
    rules:
    - apiGroups:
      - slack.stakater.com
      apiVersions:
      - v1alpha1
      operations:
      - CREATE
      - UPDATE
      resources:
      - channels
    sideEffects: null
    type: ValidatingAdmissionWebhook
    webhookPath: /validate-slack-stakater-com-v1alpha1-channel
  - admissionReviewVersions: null
    deploymentName: slack-operator-webhook
    failurePolicy: Fail
    generateName: mchannel.kb.io
    rules:
    - apiGroups:
      - slack.stakater.com
      apiVersions:
      - v1alpha1
      operations:
      - CREATE
      - UPDATE
      resources:
      - channels
    sideEffects: null
    type: MutatingAdmissionWebhook
    webhookPath: /mutate-slack-stakater-com-v1alpha1-channel
